name: "DMM Interface Release"

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_PROD_SA_KEY }}
          export_default_credentials: true

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependences
        uses: bahmutov/npm-install@HEAD

      - name: Yarn Build
        env:
          CI: false 
        run: yarn build-production

      - name: Save build
        uses: actions/upload-artifact@v2
        with: 
          name: build-production
          path: build
          if-no-files-found: error

  docker:
    needs:
      - build
    env:
      SERVICE: dmm-interface
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore build
        uses: actions/download-artifact@v2
        with:
          name: build-production
          path: build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.SERVICE }}-buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          labels: |
            org.label-schema.schema-version=1.0
            org.label-schema.vcs-ref=${{ github.sha }}
            org.label-schema.version=v${{ github.event.inputs.version }}
            org.label-schema.name=${{ env.SERVICE }}
          tags: |
            kybernetwork/${{ env.SERVICE }}:latest
            kybernetwork/${{ env.SERVICE }}:${{ github.event.inputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move Docker cache 
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache 

  upload-gcs:
    needs:
      - build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore build
        uses: actions/download-artifact@v2
        with:
          name: build-production
          path: build

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_PROD_SA_KEY }}
          export_default_credentials: true 

      - name: Upload to GCS
        env:
          BUCKET: dev-dmm.knstats.com
        run: |
          gsutil -m rsync -R $PWD/build gs://$BUCKET
          gsutil setmeta -h "Cache-Control: no-cache" gs://$BUCKET/*.html

  release:
    needs:
      - docker
      - upload-gcs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Create tag
        env: 
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git tag --annotate --message "Tag for release $VERSION" "$VERSION"
          git push origin "refs/tags/$VERSION"

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_PAT }}
          automatic_release_tag: ${{ github.event.inputs.version }}
          prerelease: false 
          title: "Dmm Interface ${{ github.event.inputs.version }}"
